#############################################################################
# Makefile for building: DarkCalculator
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  DarkCalculator.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile DarkCalculator.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DarkCalculator1.0.0
DISTDIR = /home/mrfoxy/DarkCalculator/.tmp/DarkCalculator1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Model/Arma.cpp \
		Model/ArmaFisica.cpp \
		Model/ArmaMagica.cpp \
		Model/Armamento.cpp \
		Model/Armatura.cpp \
		Model/Caratteristiche.cpp \
		Model/Equipaggiamento.cpp \
		Model/Scudo.cpp \
		View/Caratteristiche_gui.cpp \
		View/MainWindow.cpp \
		View/OperazioniArma.cpp \
		View/OperazioniArmaFisica.cpp \
		View/OperazioniArmaFisicaP2.cpp \
		View/OperazioniArmaMagica.cpp \
		View/OperazioniArmamento.cpp \
		View/OperazioniArmaP2.cpp \
		View/OperazioniArmatura.cpp \
		View/OperazioniScudo.cpp \
		View/TabArma.cpp \
		View/TabArmaFisica.cpp \
		View/TabArmaMagica.cpp \
		View/TabArmamento.cpp \
		View/TabArmatura.cpp \
		View/TabScudo.cpp \
		View/TabWidget.cpp moc_Caratteristiche_gui.cpp \
		moc_MainWindow.cpp \
		moc_OperazioniArma.cpp \
		moc_OperazioniArmaFisica.cpp \
		moc_OperazioniArmaFisicaP2.cpp \
		moc_OperazioniArmaMagica.cpp \
		moc_OperazioniArmamento.cpp \
		moc_OperazioniArmaP2.cpp \
		moc_OperazioniArmatura.cpp \
		moc_OperazioniScudo.cpp \
		moc_TabArma.cpp \
		moc_TabArmaFisica.cpp \
		moc_TabArmaMagica.cpp \
		moc_TabArmamento.cpp \
		moc_TabArmatura.cpp \
		moc_TabScudo.cpp \
		moc_TabWidget.cpp
OBJECTS       = main.o \
		Arma.o \
		ArmaFisica.o \
		ArmaMagica.o \
		Armamento.o \
		Armatura.o \
		Caratteristiche.o \
		Equipaggiamento.o \
		Scudo.o \
		Caratteristiche_gui.o \
		MainWindow.o \
		OperazioniArma.o \
		OperazioniArmaFisica.o \
		OperazioniArmaFisicaP2.o \
		OperazioniArmaMagica.o \
		OperazioniArmamento.o \
		OperazioniArmaP2.o \
		OperazioniArmatura.o \
		OperazioniScudo.o \
		TabArma.o \
		TabArmaFisica.o \
		TabArmaMagica.o \
		TabArmamento.o \
		TabArmatura.o \
		TabScudo.o \
		TabWidget.o \
		moc_Caratteristiche_gui.o \
		moc_MainWindow.o \
		moc_OperazioniArma.o \
		moc_OperazioniArmaFisica.o \
		moc_OperazioniArmaFisicaP2.o \
		moc_OperazioniArmaMagica.o \
		moc_OperazioniArmamento.o \
		moc_OperazioniArmaP2.o \
		moc_OperazioniArmatura.o \
		moc_OperazioniScudo.o \
		moc_TabArma.o \
		moc_TabArmaFisica.o \
		moc_TabArmaMagica.o \
		moc_TabArmamento.o \
		moc_TabArmatura.o \
		moc_TabScudo.o \
		moc_TabWidget.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_ContactEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_kdav.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMailTransportAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSMTP.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_Libkdepim.pri \
		/usr/lib/qt/mkspecs/modules/qt_LibkdepimAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_PimCommon.pri \
		/usr/lib/qt/mkspecs/modules/qt_PimCommonAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		DarkCalculator.pro Model/Arma.h \
		Model/ArmaFisica.h \
		Model/ArmaMagica.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Caratteristiche.h \
		Model/Equipaggiamento.h \
		Model/Scudo.h \
		View/Caratteristiche_gui.h \
		View/MainWindow.h \
		View/OperazioniArma.h \
		View/OperazioniArmaFisica.h \
		View/OperazioniArmaFisicaP2.h \
		View/OperazioniArmaMagica.h \
		View/OperazioniArmamento.h \
		View/OperazioniArmaP2.h \
		View/OperazioniArmatura.h \
		View/OperazioniScudo.h \
		View/TabArma.h \
		View/TabArmaFisica.h \
		View/TabArmaMagica.h \
		View/TabArmamento.h \
		View/TabArmatura.h \
		View/TabScudo.h \
		View/TabWidget.h main.cpp \
		Model/Arma.cpp \
		Model/ArmaFisica.cpp \
		Model/ArmaMagica.cpp \
		Model/Armamento.cpp \
		Model/Armatura.cpp \
		Model/Caratteristiche.cpp \
		Model/Equipaggiamento.cpp \
		Model/Scudo.cpp \
		View/Caratteristiche_gui.cpp \
		View/MainWindow.cpp \
		View/OperazioniArma.cpp \
		View/OperazioniArmaFisica.cpp \
		View/OperazioniArmaFisicaP2.cpp \
		View/OperazioniArmaMagica.cpp \
		View/OperazioniArmamento.cpp \
		View/OperazioniArmaP2.cpp \
		View/OperazioniArmatura.cpp \
		View/OperazioniScudo.cpp \
		View/TabArma.cpp \
		View/TabArmaFisica.cpp \
		View/TabArmaMagica.cpp \
		View/TabArmamento.cpp \
		View/TabArmatura.cpp \
		View/TabScudo.cpp \
		View/TabWidget.cpp
QMAKE_TARGET  = DarkCalculator
DESTDIR       = 
TARGET        = DarkCalculator


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DarkCalculator.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_ContactEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_kdav.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMailTransportAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSMTP.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_Libkdepim.pri \
		/usr/lib/qt/mkspecs/modules/qt_LibkdepimAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_PimCommon.pri \
		/usr/lib/qt/mkspecs/modules/qt_PimCommonAkonadi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		DarkCalculator.pro \
		/usr/lib/libQt5Widgets.prl \
		/usr/lib/libQt5Gui.prl \
		/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile DarkCalculator.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiAgentBase.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiCalendar.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiContact.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiCore.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiNotes.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiXml.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_ContactEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KAlarmCal.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCalCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KCalUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_kdav.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIBlogger.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPICalendar.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPICore.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIDrive.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPILatitude.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIMaps.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPITasks.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdentityManagement.pri:
/usr/lib/qt/mkspecs/modules/qt_KIMAP.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KMailTransport.pri:
/usr/lib/qt/mkspecs/modules/qt_KMailTransportAkonadi.pri:
/usr/lib/qt/mkspecs/modules/qt_KMime.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KontactInterface.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPIMTextEdit.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSMTP.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_Ldap.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_Libkdepim.pri:
/usr/lib/qt/mkspecs/modules/qt_LibkdepimAkonadi.pri:
/usr/lib/qt/mkspecs/modules/qt_Mbox.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_PimCommon.pri:
/usr/lib/qt/mkspecs/modules/qt_PimCommonAkonadi.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
DarkCalculator.pro:
/usr/lib/libQt5Widgets.prl:
/usr/lib/libQt5Gui.prl:
/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile DarkCalculator.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Model/Arma.h Model/ArmaFisica.h Model/ArmaMagica.h Model/Armamento.h Model/Armatura.h Model/Caratteristiche.h Model/Equipaggiamento.h Model/Scudo.h View/Caratteristiche_gui.h View/MainWindow.h View/OperazioniArma.h View/OperazioniArmaFisica.h View/OperazioniArmaFisicaP2.h View/OperazioniArmaMagica.h View/OperazioniArmamento.h View/OperazioniArmaP2.h View/OperazioniArmatura.h View/OperazioniScudo.h View/TabArma.h View/TabArmaFisica.h View/TabArmaMagica.h View/TabArmamento.h View/TabArmatura.h View/TabScudo.h View/TabWidget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Model/Arma.cpp Model/ArmaFisica.cpp Model/ArmaMagica.cpp Model/Armamento.cpp Model/Armatura.cpp Model/Caratteristiche.cpp Model/Equipaggiamento.cpp Model/Scudo.cpp View/Caratteristiche_gui.cpp View/MainWindow.cpp View/OperazioniArma.cpp View/OperazioniArmaFisica.cpp View/OperazioniArmaFisicaP2.cpp View/OperazioniArmaMagica.cpp View/OperazioniArmamento.cpp View/OperazioniArmaP2.cpp View/OperazioniArmatura.cpp View/OperazioniScudo.cpp View/TabArma.cpp View/TabArmaFisica.cpp View/TabArmaMagica.cpp View/TabArmamento.cpp View/TabArmatura.cpp View/TabScudo.cpp View/TabWidget.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Caratteristiche_gui.cpp moc_MainWindow.cpp moc_OperazioniArma.cpp moc_OperazioniArmaFisica.cpp moc_OperazioniArmaFisicaP2.cpp moc_OperazioniArmaMagica.cpp moc_OperazioniArmamento.cpp moc_OperazioniArmaP2.cpp moc_OperazioniArmatura.cpp moc_OperazioniScudo.cpp moc_TabArma.cpp moc_TabArmaFisica.cpp moc_TabArmaMagica.cpp moc_TabArmamento.cpp moc_TabArmatura.cpp moc_TabScudo.cpp moc_TabWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Caratteristiche_gui.cpp moc_MainWindow.cpp moc_OperazioniArma.cpp moc_OperazioniArmaFisica.cpp moc_OperazioniArmaFisicaP2.cpp moc_OperazioniArmaMagica.cpp moc_OperazioniArmamento.cpp moc_OperazioniArmaP2.cpp moc_OperazioniArmatura.cpp moc_OperazioniScudo.cpp moc_TabArma.cpp moc_TabArmaFisica.cpp moc_TabArmaMagica.cpp moc_TabArmamento.cpp moc_TabArmatura.cpp moc_TabScudo.cpp moc_TabWidget.cpp
moc_Caratteristiche_gui.cpp: Model/Caratteristiche.h \
		View/Caratteristiche_gui.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/Caratteristiche_gui.h -o moc_Caratteristiche_gui.cpp

moc_MainWindow.cpp: View/Caratteristiche_gui.h \
		Model/Caratteristiche.h \
		View/TabWidget.h \
		View/TabArma.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Armamento.h \
		View/OperazioniArma.h \
		View/OperazioniArmaP2.h \
		Model/ArmaFisica.h \
		Model/Armatura.h \
		Model/Scudo.h \
		Model/ArmaMagica.h \
		View/TabArmaFisica.h \
		View/OperazioniArmaFisica.h \
		View/TabArmaMagica.h \
		View/OperazioniArmaMagica.h \
		View/TabArmamento.h \
		View/OperazioniArmamento.h \
		View/TabArmatura.h \
		View/OperazioniArmatura.h \
		View/TabScudo.h \
		View/OperazioniScudo.h \
		View/MainWindow.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/MainWindow.h -o moc_MainWindow.cpp

moc_OperazioniArma.cpp: Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		View/OperazioniArma.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/OperazioniArma.h -o moc_OperazioniArma.cpp

moc_OperazioniArmaFisica.cpp: Model/ArmaFisica.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Scudo.h \
		View/OperazioniArma.h \
		View/OperazioniArmaFisica.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/OperazioniArmaFisica.h -o moc_OperazioniArmaFisica.cpp

moc_OperazioniArmaFisicaP2.cpp: View/OperazioniArmaFisicaP2.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/luca/Desktop/DarkCalcGUI/DarkCalculator -I/home/luca/Desktop/DarkCalcGUI/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/OperazioniArmaFisicaP2.h -o moc_OperazioniArmaFisicaP2.cpp

moc_OperazioniArmaMagica.cpp: Model/ArmaMagica.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Scudo.h \
		View/OperazioniArma.h \
		View/OperazioniArmaMagica.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/OperazioniArmaMagica.h -o moc_OperazioniArmaMagica.cpp

moc_OperazioniArmamento.cpp: Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		View/OperazioniArmamento.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/OperazioniArmamento.h -o moc_OperazioniArmamento.cpp

moc_OperazioniArmaP2.cpp: Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/ArmaFisica.h \
		Model/Armatura.h \
		Model/Scudo.h \
		Model/ArmaMagica.h \
		View/OperazioniArmaP2.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/OperazioniArmaP2.h -o moc_OperazioniArmaP2.cpp

moc_OperazioniArmatura.cpp: Model/Armatura.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Arma.h \
		View/OperazioniArmamento.h \
		View/OperazioniArmatura.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/OperazioniArmatura.h -o moc_OperazioniArmatura.cpp

moc_OperazioniScudo.cpp: Model/Scudo.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Arma.h \
		View/OperazioniArmamento.h \
		View/OperazioniScudo.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/OperazioniScudo.h -o moc_OperazioniScudo.cpp

moc_TabArma.cpp: Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		View/OperazioniArma.h \
		View/OperazioniArmaP2.h \
		Model/ArmaFisica.h \
		Model/Armatura.h \
		Model/Scudo.h \
		Model/ArmaMagica.h \
		View/TabArma.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/TabArma.h -o moc_TabArma.cpp

moc_TabArmaFisica.cpp: View/OperazioniArmaFisica.h \
		Model/ArmaFisica.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Scudo.h \
		View/OperazioniArma.h \
		View/TabArmaFisica.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/TabArmaFisica.h -o moc_TabArmaFisica.cpp

moc_TabArmaMagica.cpp: Model/ArmaMagica.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Scudo.h \
		View/OperazioniArmaMagica.h \
		View/OperazioniArma.h \
		View/TabArmaMagica.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/TabArmaMagica.h -o moc_TabArmaMagica.cpp

moc_TabArmamento.cpp: Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		View/OperazioniArmamento.h \
		View/TabArmamento.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/TabArmamento.h -o moc_TabArmamento.cpp

moc_TabArmatura.cpp: View/TabArmamento.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		View/OperazioniArmamento.h \
		Model/Armatura.h \
		Model/Arma.h \
		View/OperazioniArmatura.h \
		View/TabArmatura.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/TabArmatura.h -o moc_TabArmatura.cpp

moc_TabScudo.cpp: View/TabArmamento.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		View/OperazioniArmamento.h \
		Model/Scudo.h \
		Model/Arma.h \
		View/OperazioniScudo.h \
		View/TabScudo.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/TabScudo.h -o moc_TabScudo.cpp

moc_TabWidget.cpp: View/TabArma.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		View/OperazioniArma.h \
		View/OperazioniArmaP2.h \
		Model/ArmaFisica.h \
		Model/Armatura.h \
		Model/Scudo.h \
		Model/ArmaMagica.h \
		View/TabArmaFisica.h \
		View/OperazioniArmaFisica.h \
		View/TabArmaMagica.h \
		View/OperazioniArmaMagica.h \
		View/TabArmamento.h \
		View/OperazioniArmamento.h \
		View/TabArmatura.h \
		View/OperazioniArmatura.h \
		View/TabScudo.h \
		View/OperazioniScudo.h \
		View/TabWidget.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/mrfoxy/DarkCalculator -I/home/mrfoxy/DarkCalculator -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.3.1 -I/usr/include/c++/7.3.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.3.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include-fixed -I/usr/include View/TabWidget.h -o moc_TabWidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp View/MainWindow.h \
		View/Caratteristiche_gui.h \
		Model/Caratteristiche.h \
		View/TabWidget.h \
		View/TabArma.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Armamento.h \
		View/OperazioniArma.h \
		View/OperazioniArmaP2.h \
		Model/ArmaFisica.h \
		Model/Armatura.h \
		Model/Scudo.h \
		Model/ArmaMagica.h \
		View/TabArmaFisica.h \
		View/OperazioniArmaFisica.h \
		View/TabArmaMagica.h \
		View/OperazioniArmaMagica.h \
		View/TabArmamento.h \
		View/OperazioniArmamento.h \
		View/TabArmatura.h \
		View/OperazioniArmatura.h \
		View/TabScudo.h \
		View/OperazioniScudo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Arma.o: Model/Arma.cpp Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Arma.o Model/Arma.cpp

ArmaFisica.o: Model/ArmaFisica.cpp Model/ArmaFisica.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Scudo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ArmaFisica.o Model/ArmaFisica.cpp

ArmaMagica.o: Model/ArmaMagica.cpp Model/ArmaMagica.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Scudo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ArmaMagica.o Model/ArmaMagica.cpp

Armamento.o: Model/Armamento.cpp Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Armamento.o Model/Armamento.cpp

Armatura.o: Model/Armatura.cpp Model/Armatura.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Arma.h \
		Model/ArmaFisica.h \
		Model/Scudo.h \
		Model/ArmaMagica.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Armatura.o Model/Armatura.cpp

Caratteristiche.o: Model/Caratteristiche.cpp Model/Caratteristiche.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Caratteristiche.o Model/Caratteristiche.cpp

Equipaggiamento.o: Model/Equipaggiamento.cpp Model/Equipaggiamento.h \
		Model/Caratteristiche.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Equipaggiamento.o Model/Equipaggiamento.cpp

Scudo.o: Model/Scudo.cpp Model/Scudo.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Arma.h \
		Model/ArmaFisica.h \
		Model/Armatura.h \
		Model/ArmaMagica.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scudo.o Model/Scudo.cpp

Caratteristiche_gui.o: View/Caratteristiche_gui.cpp View/Caratteristiche_gui.h \
		Model/Caratteristiche.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Caratteristiche_gui.o View/Caratteristiche_gui.cpp

MainWindow.o: View/MainWindow.cpp View/MainWindow.h \
		View/Caratteristiche_gui.h \
		Model/Caratteristiche.h \
		View/TabWidget.h \
		View/TabArma.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Armamento.h \
		View/OperazioniArma.h \
		View/OperazioniArmaP2.h \
		Model/ArmaFisica.h \
		Model/Armatura.h \
		Model/Scudo.h \
		Model/ArmaMagica.h \
		View/TabArmaFisica.h \
		View/OperazioniArmaFisica.h \
		View/TabArmaMagica.h \
		View/OperazioniArmaMagica.h \
		View/TabArmamento.h \
		View/OperazioniArmamento.h \
		View/TabArmatura.h \
		View/OperazioniArmatura.h \
		View/TabScudo.h \
		View/OperazioniScudo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o View/MainWindow.cpp

OperazioniArma.o: View/OperazioniArma.cpp View/OperazioniArma.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OperazioniArma.o View/OperazioniArma.cpp

OperazioniArmaFisica.o: View/OperazioniArmaFisica.cpp View/OperazioniArmaFisica.h \
		Model/ArmaFisica.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Scudo.h \
		View/OperazioniArma.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OperazioniArmaFisica.o View/OperazioniArmaFisica.cpp

OperazioniArmaFisicaP2.o: View/OperazioniArmaFisicaP2.cpp View/OperazioniArmaFisicaP2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OperazioniArmaFisicaP2.o View/OperazioniArmaFisicaP2.cpp

OperazioniArmaMagica.o: View/OperazioniArmaMagica.cpp View/OperazioniArmaMagica.h \
		Model/ArmaMagica.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Scudo.h \
		View/OperazioniArma.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OperazioniArmaMagica.o View/OperazioniArmaMagica.cpp

OperazioniArmamento.o: View/OperazioniArmamento.cpp View/OperazioniArmamento.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OperazioniArmamento.o View/OperazioniArmamento.cpp

OperazioniArmaP2.o: View/OperazioniArmaP2.cpp View/OperazioniArmaP2.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/ArmaFisica.h \
		Model/Armatura.h \
		Model/Scudo.h \
		Model/ArmaMagica.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OperazioniArmaP2.o View/OperazioniArmaP2.cpp

OperazioniArmatura.o: View/OperazioniArmatura.cpp View/OperazioniArmatura.h \
		Model/Armatura.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Arma.h \
		View/OperazioniArmamento.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OperazioniArmatura.o View/OperazioniArmatura.cpp

OperazioniScudo.o: View/OperazioniScudo.cpp View/OperazioniScudo.h \
		Model/Scudo.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Arma.h \
		View/OperazioniArmamento.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OperazioniScudo.o View/OperazioniScudo.cpp

TabArma.o: View/TabArma.cpp View/TabArma.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		View/OperazioniArma.h \
		View/OperazioniArmaP2.h \
		Model/ArmaFisica.h \
		Model/Armatura.h \
		Model/Scudo.h \
		Model/ArmaMagica.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabArma.o View/TabArma.cpp

TabArmaFisica.o: View/TabArmaFisica.cpp View/TabArmaFisica.h \
		View/OperazioniArmaFisica.h \
		Model/ArmaFisica.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Scudo.h \
		View/OperazioniArma.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabArmaFisica.o View/TabArmaFisica.cpp

TabArmaMagica.o: View/TabArmaMagica.cpp View/TabArmaMagica.h \
		Model/ArmaMagica.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		Model/Armatura.h \
		Model/Scudo.h \
		View/OperazioniArmaMagica.h \
		View/OperazioniArma.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabArmaMagica.o View/TabArmaMagica.cpp

TabArmamento.o: View/TabArmamento.cpp View/TabArmamento.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		View/OperazioniArmamento.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabArmamento.o View/TabArmamento.cpp

TabArmatura.o: View/TabArmatura.cpp View/TabArmatura.h \
		View/TabArmamento.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		View/OperazioniArmamento.h \
		Model/Armatura.h \
		Model/Arma.h \
		View/OperazioniArmatura.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabArmatura.o View/TabArmatura.cpp

TabScudo.o: View/TabScudo.cpp View/TabScudo.h \
		View/TabArmamento.h \
		Model/Armamento.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		View/OperazioniArmamento.h \
		Model/Scudo.h \
		Model/Arma.h \
		View/OperazioniScudo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabScudo.o View/TabScudo.cpp

TabWidget.o: View/TabWidget.cpp View/TabWidget.h \
		View/TabArma.h \
		Model/Arma.h \
		Model/Equipaggiamento.h \
		Model/Caratteristiche.h \
		Model/Armamento.h \
		View/OperazioniArma.h \
		View/OperazioniArmaP2.h \
		Model/ArmaFisica.h \
		Model/Armatura.h \
		Model/Scudo.h \
		Model/ArmaMagica.h \
		View/TabArmaFisica.h \
		View/OperazioniArmaFisica.h \
		View/TabArmaMagica.h \
		View/OperazioniArmaMagica.h \
		View/TabArmamento.h \
		View/OperazioniArmamento.h \
		View/TabArmatura.h \
		View/OperazioniArmatura.h \
		View/TabScudo.h \
		View/OperazioniScudo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TabWidget.o View/TabWidget.cpp

moc_Caratteristiche_gui.o: moc_Caratteristiche_gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Caratteristiche_gui.o moc_Caratteristiche_gui.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_OperazioniArma.o: moc_OperazioniArma.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OperazioniArma.o moc_OperazioniArma.cpp

moc_OperazioniArmaFisica.o: moc_OperazioniArmaFisica.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OperazioniArmaFisica.o moc_OperazioniArmaFisica.cpp

moc_OperazioniArmaFisicaP2.o: moc_OperazioniArmaFisicaP2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OperazioniArmaFisicaP2.o moc_OperazioniArmaFisicaP2.cpp

moc_OperazioniArmaMagica.o: moc_OperazioniArmaMagica.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OperazioniArmaMagica.o moc_OperazioniArmaMagica.cpp

moc_OperazioniArmamento.o: moc_OperazioniArmamento.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OperazioniArmamento.o moc_OperazioniArmamento.cpp

moc_OperazioniArmaP2.o: moc_OperazioniArmaP2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OperazioniArmaP2.o moc_OperazioniArmaP2.cpp

moc_OperazioniArmatura.o: moc_OperazioniArmatura.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OperazioniArmatura.o moc_OperazioniArmatura.cpp

moc_OperazioniScudo.o: moc_OperazioniScudo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OperazioniScudo.o moc_OperazioniScudo.cpp

moc_TabArma.o: moc_TabArma.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TabArma.o moc_TabArma.cpp

moc_TabArmaFisica.o: moc_TabArmaFisica.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TabArmaFisica.o moc_TabArmaFisica.cpp

moc_TabArmaMagica.o: moc_TabArmaMagica.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TabArmaMagica.o moc_TabArmaMagica.cpp

moc_TabArmamento.o: moc_TabArmamento.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TabArmamento.o moc_TabArmamento.cpp

moc_TabArmatura.o: moc_TabArmatura.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TabArmatura.o moc_TabArmatura.cpp

moc_TabScudo.o: moc_TabScudo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TabScudo.o moc_TabScudo.cpp

moc_TabWidget.o: moc_TabWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TabWidget.o moc_TabWidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

